spring.application.name=plant-api
# Set these as environment variables locally and on deployment paltform:
#   SPRING_DATASOURCE_URL="YOUR _NEON_DATABASE_URL"
# Spring Boot reads those names automatically, so nothing secret lives in this file.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=${PORT:8080}
